name: CI and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18 # Update to node version 16 or node version 20

    - name: Install dependencies
      run: npm install


    - name: Build project
      run: |
          echo "Building the project..."
          CI=false npm run build
          echo "Build completed"

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.TOKEN_GITHUB }}
        publish_dir: ./build
